export { createApiClient } from "./client";
export type {
  ApiClient,
  ApiClientConfig,
  AdminContactMessage,
  AdminContentReport,
  AdminUserRow,
  AdminUsersByRole,
  AuthResult,
  ClientBooking,
  ClientGuidedRequest,
  CurrentUser,
  // MANOVIA — fiscale, pagamenti, DAC7 (CLAUDE.md §88).
  JobPayment,
  JobPaymentMethod,
  JobPaymentStatus,
  FiscalVerificationStatus,
  ProfessionalFiscalProfile,
  AuditLogEntry,
  AdminFiscalView,
  PlatformFeeRule,
  Dac7ReportingStatus,
  Dac7ReportingPeriod,
  Dac7Record,
  AdminFinanceSummary,
} from "./client";
